import FadeIn from "@/Components/Animations/FadeIn";
import Card from "@/Components/Common/Card";
import PrimaryButton from "@/Components/PrimaryButton";
import { QUESTION_TYPES } from "@/constants/questionTypes";
import { useSurveyBuilder } from "@/contexts/SurveyBuilderContext";
import { QuestionType } from "@/types/surveyBuilder";
import {
    closestCenter,
    DndContext,
    DragEndEvent,
    KeyboardSensor,
    PointerSensor,
    useSensor,
    useSensors,
} from "@dnd-kit/core";
import {
    arrayMove,
    SortableContext,
    sortableKeyboardCoordinates,
    verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { Eye, Plus } from "lucide-react";
import { useState } from "react";
import QuestionTypeSelector from "./QuestionTypeSelector";
import SortableThemeItem from "./SortableThemeItem";

export default function SurveyBuilder() {
    const { state, addTheme, addQuestion, setStep, reorderThemes } =
        useSurveyBuilder();
    const [selectedThemeId, setSelectedThemeId] = useState<string | null>(null);
    const [showQuestionTypes, setShowQuestionTypes] = useState(false);

    // Drag & drop sensors for themes
    const sensors = useSensors(
        useSensor(PointerSensor, {
            activationConstraint: {
                distance: 8,
            },
        }),
        useSensor(KeyboardSensor, {
            coordinateGetter: sortableKeyboardCoordinates,
        })
    );

    const handleAddQuestion = (themeId: string) => {
        setSelectedThemeId(themeId);
        setShowQuestionTypes(true);
    };

    const handleSelectQuestionType = (type: QuestionType) => {
        if (!selectedThemeId) return;

        const config = QUESTION_TYPES.find((t) => t.type === type);
        if (config) {
            addQuestion(selectedThemeId, {
                ...config.defaultConfig,
                id: "", // Will be generated by context
            });
            setShowQuestionTypes(false);
            setSelectedThemeId(null);
        }
    };

    const handleThemeDragEnd = (event: DragEndEvent) => {
        const { active, over } = event;

        if (!over || active.id === over.id) {
            return;
        }

        const oldIndex = state.themes.findIndex((t) => t.id === active.id);
        const newIndex = state.themes.findIndex((t) => t.id === over.id);

        if (oldIndex === -1 || newIndex === -1) {
            console.error("Theme not found during drag");
            return;
        }

        const newOrder = arrayMove(state.themes, oldIndex, newIndex);
        reorderThemes(newOrder.map((t) => t.id));
    };

    const handleNext = () => {
        if (state.themes.length === 0) {
            alert("Veuillez ajouter au moins un thème avec une question");
            return;
        }

        const hasQuestions = state.themes.some(
            (theme) => theme.questions.length > 0
        );
        if (!hasQuestions) {
            alert("Veuillez ajouter au moins une question à un thème");
            return;
        }

        setStep("preview");
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-6 px-4 sm:px-6 lg:px-8 py-4 sm:py-6">
            {/* Main area - Themes */}
            <div className="space-y-6">
                {/* Header */}
                <FadeIn delay={0}>
                    <div className="flex items-center justify-between">
                        <div>
                            <h2 className="text-lg sm:text-xl font-semibold text-gray-900">
                                Construction de l'enquête
                            </h2>
                            <p className="text-sm text-gray-600 mt-1">
                                Organisez vos questions en thèmes
                            </p>
                        </div>
                        <button
                            onClick={addTheme}
                            className="inline-flex items-center gap-2 px-4 py-2 bg-white border-2 border-elan-orange text-elan-orange rounded-lg hover:bg-elan-orange hover:text-white transition-colors text-sm font-medium"
                        >
                            <Plus className="w-4 h-4" />
                            <span className="hidden sm:inline">
                                Ajouter un thème
                            </span>
                            <span className="sm:hidden">Thème</span>
                        </button>
                    </div>
                </FadeIn>

                {/* Themes list */}
                {state.themes.length === 0 ? (
                    <FadeIn delay={100}>
                        <Card>
                            <div className="text-center py-12">
                                <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                    <Plus className="w-8 h-8 text-gray-400" />
                                </div>
                                <h3 className="text-lg font-medium text-gray-900 mb-2">
                                    Aucun thème créé
                                </h3>
                                <p className="text-sm text-gray-600 mb-4">
                                    Commencez par créer un thème pour organiser
                                    vos questions
                                </p>
                                <button
                                    onClick={addTheme}
                                    className="inline-flex items-center gap-2 px-6 py-3 bg-elan-orange text-white rounded-lg hover:bg-elan-orange/90 transition-colors font-medium"
                                >
                                    <Plus className="w-5 h-5" />
                                    Créer le premier thème
                                </button>
                            </div>
                        </Card>
                    </FadeIn>
                ) : (
                    <div className="space-y-6">
                        <DndContext
                            sensors={sensors}
                            collisionDetection={closestCenter}
                            onDragEnd={handleThemeDragEnd}
                        >
                            <SortableContext
                                items={state.themes.map((t) => t.id)}
                                strategy={verticalListSortingStrategy}
                            >
                                {state.themes.map((theme, index) => (
                                    <FadeIn
                                        key={theme.id}
                                        delay={100 + index * 50}
                                    >
                                        <SortableThemeItem
                                            theme={theme}
                                            onAddQuestion={() =>
                                                handleAddQuestion(theme.id)
                                            }
                                            index={index}
                                        />
                                    </FadeIn>
                                ))}
                            </SortableContext>
                        </DndContext>
                    </div>
                )}

                {/* Navigation buttons */}
                {state.themes.length > 0 && (
                    <FadeIn delay={200}>
                        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-4">
                            <button
                                onClick={() => setStep("info")}
                                className="px-4 py-2 text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors order-2 sm:order-1"
                            >
                                ← Retour aux informations
                            </button>
                            <PrimaryButton
                                onClick={handleNext}
                                className="order-1 sm:order-2 justify-center"
                            >
                                <Eye className="w-4 h-4 mr-2" />
                                Aperçu et publication
                            </PrimaryButton>
                        </div>
                    </FadeIn>
                )}
            </div>

            {/* Sidebar - Question types */}
            <div className="lg:sticky lg:top-6 lg:h-fit">
                <FadeIn delay={150}>
                    {showQuestionTypes ? (
                        <Card padding="sm">
                            <div className="mb-4">
                                <button
                                    onClick={() => {
                                        setShowQuestionTypes(false);
                                        setSelectedThemeId(null);
                                    }}
                                    className="text-sm text-gray-600 hover:text-gray-900"
                                >
                                    ← Annuler
                                </button>
                            </div>
                            <QuestionTypeSelector
                                onSelect={handleSelectQuestionType}
                            />
                        </Card>
                    ) : (
                        <Card padding="sm">
                            <div className="text-center py-8">
                                <p className="text-sm text-gray-500 mb-3">
                                    Cliquez sur "Ajouter une question" dans un
                                    thème pour choisir le type
                                </p>
                                <div className="text-xs text-gray-400">
                                    8 types de questions disponibles
                                </div>
                            </div>
                        </Card>
                    )}
                </FadeIn>
            </div>
        </div>
    );
}
